### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by jordsta95** [TemporalReality/Launcher#8]
Execute Jar file, popup appears:
"A Java Exception has occured"

**Comment by coolsquid** [comment]
Your Java exception is caused by the fact that our pack index hasn't been created. Works fine for me, and I'm on Windows.

**Comment by RX14** [comment]
You shouldn't call random people invalids @shadowfacts

**Comment by shadowfacts** [comment]
Goddamnit, @RX14, the issue is invalid.
